services:
  api:
    build: .
    container_name: urbreath_optimal_snow
    ports:
      - "8003:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .data_prepared:/app/data_prepared
    restart: always